# MySQL.  Versions 5.0+ are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: <%= ENV['AATH_SEARCH_DB_NAME'] %>
  username: <%= ENV['AATH_SEARCH_DB_USERNAME'] %>
  password: <%= ENV['AATH_SEARCH_DB_PASSWORD'] %>
  database: <%= ENV['AATH_SEARCH_DB_NAME'] %>
  encoding:  utf8mb4
  collation: utf8mb4_unicode_ci

development:
  <<: *default
  host:     <%= ENV['AATH_SEARCH_DB_HOST'] %>

test:
  <<: *default
  database: aath_search_test

production:
  <<: *default
  pool: 20
  host: <%= ENV['AATH_SEARCH_DB_HOST'] %>
